### PR TITLE
ci: add 3.13 tests and classifier

### PR DESCRIPTION
**Pull request by henryiii**
Can we change the default branch to `main`? It's currently some old back port branch.

### CODE REVIEW

**Comment by henryiii** [comment]
Any idea what's pulling pyarrow? Ahh, papermill is.

**Comment by henryiii** [comment]
Just removed Papermill since it was commented out and unused.

**Comment by jonas-eschle** [comment]
> Can we change the default branch to `main`? It's currently some old back port branch.

Yes, this was a bit buggy and wouldn't switch to main, but done now.

Looks all got to me, thanks a lot @henryiii

**Comment by jonas-eschle** [comment]
@henryiii good point, done

**Pull request merged**
