### PR TITLE
Allow single-histogram stacks

### LINKED ISSUE #129: Stacking a single histogram
Hi,

I am wondering about the explicit check of the number of histograms in a stack [here](https://github.com/scikit-hep/mplhep/blob/master/mplhep/plot.py#L140-L141). 

I run into this check a lot when I e.g. select datasets in my coffea histograms to be overlaid using a regular expression. In order to produce many plots in an automated way, I'd  like to be able to use the same plotting code whether my regex matches 1 or N>1 data sets.

I tried simply removing the check and the code runs fine, which is also what  I'd have expected since a single-histogram stack is well-defined. Are there any strong reasons to abort plotting in this case?

### PR DESCRIPTION
**Pull request by AndreasAlbert**
Closes #129

### CODE REVIEW

**Comment by andrzejnovak** [comment]
@AndreasAlbert Can you ammend the commit message to be compatible with https://www.conventionalcommits.org/en/v1.0.0/

**Comment by AndreasAlbert** [comment]
Let's try again

**Comment by andrzejnovak** [comment]
Thanks! I guess the release action gets hung up on something else. I'm gonna push a release manually.

@matthewfeickert Can you take a look at what could be tripping bump version up? I'm confused where this is coming from 
```
Run git merge --squash "origin/${GITHUB_HEAD_REF}"
merge: origin/2020-04-25_stack_single_hist - not something we can merge
```

**Comment by matthewfeickert** [comment]
> Can you take a look at what could be tripping bump version up? I'm confused where this is coming from

Hey. Yeah, the way that we originally wrote this assumed that @kratsg, @lukasheinrich, and I (the core devs) would be the only people to be making releases. Looking at [the logs](https://github.com/scikit-hep/mplhep/runs/630623966#step:8:1)

```
  git merge --squash "origin/${GITHUB_HEAD_REF}"
  git commit -m "${PR_TITLE} (#${PR_NUMBER})"
  shell: /bin/bash -e {0}
  env:
    IS_MAJOR: false
    IS_MINOR: false
    IS_PATCH: true
    PR_NUMBER: 133
    PR_TITLE: Allow single-histogram stacks
    GITHUB_HEAD_REF: 2020-04-25_stack_single_hist
    BV_PART: patch
merge: origin/2020-04-25_stack_single_hist - not something we can merge
```

this makes sense as `origin/2020-04-25_stack_single_hist` **doesn't exist** &mdash; it exists only on @AndreasAlbert's fork under that name. [GitHub Actions views this as `pull/133/merge`](https://github.com/scikit-hep/mplhep/runs/630623966#step:5:384).

I don't want to dictate a release schedule to you, but this seems a bit excessive to get its own patch release. If you want to be able to make a new patch from any incoming PR then the CI is going to have to get rewritten and without having looked at it in a while I'm not sure how hard that will be to debug. It might be easier for you to create a throwaway repo to test this all out with fake releases that never deploy.

**Comment by andrzejnovak** [comment]
Ah, I understand now. So the catch was that a new release can only be done from a PR, where the branch lives in origin. I guess that makes sense. 

Based on what you said, it looks like it should be easy enough fix though. Just changing https://github.com/scikit-hep/mplhep/blob/master/.github/workflows/tag.yml#L54 to instead take the PR ref, https://github.com/scikit-hep/mplhep/runs/630623966#step:5:384  That is I one can merge a ref, but I am assuming yes.

**Comment by kratsg** [comment]
Yes, change it to `refs/pull/${PR_NUMBER}/merge" and it should be ok.

**Pull request merged**
