### PR TITLE
Add notebooks to tests

### PR DESCRIPTION
**Pull request by matthewfeickert**
Use [papermill](https://github.com/nteract/papermill) to add testing of Jupyter notebooks.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@andrzejnovak This is ready for review.

**Comment by andrzejnovak** [comment]
Let me test how this works, because I haven't seen it before. But I like the idea of example notebooks also being tests.

**Comment by matthewfeickert** [comment]
> Let me test how this works, because I haven't seen it before. But I like the idea of example notebooks also being tests.

Sure. [Papermill](https://github.com/nteract/papermill) is kinda fantstic as it allows you to execute a Jupyter notebook from outside the kernel and with [scrapbook](https://github.com/nteract/scrapbook) you can actually collect output from the notebook that papermill is executing. It is really nice.

We on the pyhf team us it to [test all of our example notebooks](https://github.com/diana-hep/pyhf/blob/4df46d60267e14075e15b503e9285eea444a8ebc/tests/test_notebooks.py) and @betatim of Jupyter/Binder has a [nice talk that mentions papermill from Swiss Python Summit 2018](https://youtu.be/USb6ju7ApSs).

**Comment by andrzejnovak** [comment]
@matthewfeickert So is the point of this just making sure notebooks are executable top-down?

**Comment by matthewfeickert** [comment]
> So is the point of this just making sure notebooks are executable top-down?

Yes, though more importantly, if there is a PR that introduces API changes this also catches if any of the examples in the notebook would break as a result. So it gives you confidence that your examples will _always_ be up to date, as they must be by definition as you executed them.

**Comment by andrzejnovak** [comment]
Ok, I understand better now. Thanks.

**Pull request merged**
