### PR TITLE
ci: Add Python 3.11 to testing

### PR DESCRIPTION
**Pull request by matthewfeickert**
```
* Update actions to latest releases.
* Add Python 3.11 to testing in CI.
* Include version classifiers.
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
CI is failing for unrelated reasons, so that needs to be fixed first.

**Comment by andrzejnovak** [comment]
Wow, things have been failing for a while, though it looks like an issue with `pytest-mpl`

**Comment by andrzejnovak** [comment]
@matthewfeickert can you rebase this? I don't seem to see the usual button.

**Comment by matthewfeickert** [comment]
Sure!

> I don't seem to see the usual button.

I enabled the "Always suggest updating pull request branches" option in settings, so the button will be there now. :+1:

**Comment by andrzejnovak** [comment]
Thanks!

**Pull request merged**
