### PR TITLE
docs: switch docs to pydata theme, add initial gallery, add some type checks

### PR DESCRIPTION
**Pull request by jonas-eschle**
Change to pydata and add a gallery top level as discussed in #405

### CODE REVIEW

**Comment by andrzejnovak** [comment]
Hmm, the Gallery doesn't seem to show up in the docs preview

**Comment by jonas-eschle** [comment]
Yep, not yet, it's still WIP, I fixed it now and added a small example (but at this point, I am not great with Sphinx tbh to create something nice)

**Comment by jonas-eschle** [comment]
Hi @andrzejnovak , I've finally added something more useful to the gallery, it shows up and has two examples. It's probably not the most elegant way, but alas, better than nothing and gives a good idea of what is available.

Also fixed some typos here and there, the docs compile now without errors/warnings

**Comment by jonas-eschle** [comment]
Okay, that was tricky with the path. Now sphinx complains, but it works. Before, it didn't complain and the pathes didn't work.

Better complaining and working than the other way around. Probably needs some better structure. But as said, it's there and works for now, provides a good overview in a simple manner.

**Pull request merged**
